### PR TITLE
Fix regression issues related to `export`

### LINKED ISSUE #66: Fix regression issues related to `export`

### PR DESCRIPTION
**Pull request by frymash**
After the `tags` field in AddressBook.json was introduced, `ExportCommand.readAndParseJson` broke because its RegEx formulas did not account for array fields.

Since `readAndParseJson` broke, the JSON could not be parsed and its data could not be written to `AddressBook.csv`. As a result, invoking export format/csv in the CLI would create a blank `AddressBook.csv`.

Let's refactor the `readAndParseJson` function to account for tags while making the implementation more intuitive. The RegEx-first approach will be replaced by an implementation that uses the Jackson API to process JSON data. We will also update the tests for `readAndParseJson` and `extractHeaders` to account for the `tags` field.

Removing RegEx is our first step to reinforcing the robustness of the implementation. If we introduce more complex fields in the future, the RegEx patterns required to process AddressBook.json could become more complex and difficult to maintain. On the other hand, the Jackson API was designed to handle JSON files. In the context of this function, Jackson functions are easier to use, faster, and more flexible than a RegEx implementation.

Resolves #66.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ExportCommand.java [hunk 1]
```diff
@@ -63,25 +67,35 @@ public CommandResult execute(Model model) throws CommandException {
...
-        while (personMatcher.find()) {
-            String personString = personMatcher.group(1);
-            Map<String, String> personData = new LinkedHashMap<>();
-            Pattern kvPattern = Pattern.compile("\"(\\w+)\"\\s*:\\s*\"([^\"]*)\"");
-            Matcher kvMatcher = kvPattern.matcher(personString);
-            while (kvMatcher.find()) {
-                String key = kvMatcher.group(1);
-                String value = kvMatcher.group(2);
-                personData.put(key, value);
-            }
```
Comment (DiegoTheExplorar) [inline src/main/java/seedu/address/logic/commands/ExportCommand.java:80]: Good job identifying the source of regression

File: src/main/java/seedu/address/logic/commands/ExportCommand.java [hunk 2]
```diff
@@ -63,25 +67,35 @@ public CommandResult execute(Model model) throws CommandException {
...
+            Map<String, String> personInfo = new LinkedHashMap<>();
+
+            person.fields().forEachRemaining(entry -> {
+                String header = entry.getKey(); // e.g. name, email, tags, etc.
+                JsonNode value = entry.getValue(); // e.g. the value associated with the header
+
+                // isTextual checks if a JsonNode represents a basic JSON String value.
+                if (value.isTextual()) {
+                    personInfo.put(header, value.asText());
+                // Note that the tags in AddressBook.json are stored in an array literal.
```
Comment (RyanWarwick) [inline src/main/java/seedu/address/logic/commands/ExportCommand.java:85]: Nice find! It's good to account for the various possible data structures when parsing in our case. Perhaps we can have some internal documentation for this in the future (i.e. String literals, Array of Objects, Map etc)
