### PR TITLE
Fix whitespace trimming bug in ExportCommand

### LINKED ISSUE #192: Export tag values end with r
image

### PR DESCRIPTION
**Pull request by frymash**
This fix resolves #192 and #246, but I'll need you guys to try checking out the PR first before we merge it.

`gh pr checkout 219`

--

When `export` is used, trailing `r`s appear in tag values in the exported files. This visual bug occurs because Windows-style newlines include carriage returns `\r`. Currently, carriage returns are not accounted for by the tag parser (`parseTags`) in `ExportCommand`.

This PR fixes the issue and refactors `parseTags` for readability. Minor edits have also been made to other parts of `ExportCommand`.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ExportCommand.java [hunk 1]
```diff
@@ -101,25 +105,20 @@ public CommandResult execute(Model model) throws CommandException {
...
+                .trim();
+        // Split the tagString; the first part represents the tag's key.
+        // If there's a second part, it represents the tag's value.
+        String[] parts = tagString.split(":");
+        boolean tagHasValue = parts.length == 2;
+        String trimmedKey = parts[0].trim();
+        if (tagHasValue) {
+            String trimmedValue = parts[1].trim();
+            return trimmedKey + " : " + trimmedValue;
         }
```
Comment (DiegoTheExplorar) [inline src/main/java/seedu/address/logic/commands/ExportCommand.java:122]: BRILLIANT Isaac. This is huge. Nice fix {insert thumbs up emoji}

**Review by DiegoTheExplorar — APPROVED** [review]
